lib/oauth2Google_web/router.ex
defmodule Oauth2GoogleWeb.Router do
  use Oauth2GoogleWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Oauth2GoogleWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController


  end


    scope "/auth", Oauth2GoogleWeb do
      pipe_through :browser # Use the default browser stack


      get "/:provider", AuthController, :index
      get "/:provider/callback", AuthController, :callback
      delete "/logout", AuthController, :delete

    end

    defp assign_current_user(conn, _) do
      assign(conn, :current_user, get_session(conn, :current_user))
    end
  # Other scopes may use custom stacks.
  # scope "/api", Oauth2GoogleWeb do
  #   pipe_through :api
  # end
end

lib/oauth2Google/application.ex
defmodule Oauth2Google.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Oauth2Google.Repo, []),
      # Start the endpoint when the application starts
      supervisor(Oauth2GoogleWeb.Endpoint, []),
      # Start your own worker by calling: Oauth2Google.Worker.start_link(arg1, arg2, arg3)
      # worker(Oauth2Google.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Oauth2Google.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    Oauth2GoogleWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/oauth2Google/repo.ex
defmodule Oauth2Google.Repo do
  use Ecto.Repo, otp_app: :oauth2Google

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/oauth2Google_web/controllers/auth_controller.ex
defmodule Oauth2GoogleWeb.AuthController do
  use  Oauth2GoogleWeb, :controller
  alias Oauth2Google.Accounts.User
  alias Oauth2Google.Repo
  @doc """
 This action is reached via `/auth/:provider` and redirects to the OAuth2 provider
 based on the chosen strategy.
 """
 def index(conn, %{"provider" => provider}) do
   redirect conn, external: authorize_url!(provider)
 end

 def delete(conn, _params) do
   conn
   |> put_flash(:info, "You have been logged out!")
   |> configure_session(drop: true)
   |> redirect(to: "/")
 end

 @doc """
 This action is reached via `/auth/:provider/callback` is the the callback URL that
 the OAuth2 provider will redirect the user back to with a `code` that will
 be used to request an access token. The access token will then be used to
 access protected resources on behalf of the user.
 """
 def callback(conn, %{"provider" => provider, "code" => code}) do
   client = get_token!(provider, code)
   IO.puts("++++++++++++")
   IO.inspect(client)
   user = get_user!(provider, client)

   IO.puts("++++++++++++")
   IO.inspect(conn.assigns)
   IO.puts("++++++++++++")
IO.inspect(user)
IO.puts("++++++++++++")
IO.inspect(provider)
IO.puts("++++++++++++")
IO.inspect(client)

   conn
   |> put_session(:current_user, user)
   |> put_session(:access_token, client.token.access_token)
   |> redirect(to: "/")

   user_params = %{token: client.token.access_token, email: user.email, provider: provider}
   changeset = User.changeset(%User{}, user_params)
   signin(conn,changeset)
 end

 defp signin(conn, changeset) do
   case insert_or_update_user(changeset) do
     {:ok, user} ->
       conn
       |> put_flash(:info, "Welcome back!")
       |> put_session(:user_id, user.id)
       |> redirect(to: "/")

     {:error, _reason} ->
       conn
       |> put_flash(:error, "Error signing in")
       |> redirect(to: "/")
   end
 end

 defp insert_or_update_user(changeset) do
  # changes is a property of changeset
  case Repo.get_by(User, email: changeset.changes.email) do
    nil ->
      Repo.insert(changeset)
    user ->
      {:ok, user} #adding :ok atom as for insert we are returned a tuple
  end
end

  defp authorize_url!("github"),   do: GitHub.authorize_url!
 defp authorize_url!("google"),   do: Google.authorize_url!(scope: "https://www.googleapis.com/auth/userinfo.email")
 defp authorize_url!("facebook"), do: Facebook.authorize_url!(scope: "email,public_profile")
 defp authorize_url!(_), do: raise "No matching provider available"

 defp get_token!("google", code),   do: Google.get_token!(code: code)
 defp get_token!("github", code),   do: GitHub.get_token!(code: code)
 defp get_token!("facebook", code), do: Facebook.get_token!(code: code)
 defp get_token!(_, _), do: raise "No matching provider available"

 defp get_user!("github", client) do
   %{body: user} = OAuth2.Client.get!(client, "/user")
   %{name: user["name"], avatar: user["avatar_url"], email: user["email"]}
 end

 defp get_user!("google", client) do
   %{body: user, status_code: status} = OAuth2.Client.get!(client, "https://www.googleapis.com/plus/v1/people/me/openIdConnect")
   %{name: user["name"], domain: user["hd"], email_verified: user["email_verified"], avatar: user["picture"], email: user["email"]}
 end

 defp get_user!("facebook", client) do
   IO.puts("++++++++++ client")
   IO.inspect(client)
   IO.puts("++++++++++")
   %{body: user} = OAuth2.Client.get!(client, "/me")
   IO.inspect(user)
   %{name: user["name"], avatar: "https://graph.facebook.com/#{user["id"]}/picture", email: user["email"]}
 end
end

lib/oauth2Google_web/controllers/page_controller.ex
defmodule Oauth2GoogleWeb.PageController do
  use  Oauth2GoogleWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/oauth2Google_web/views/error_view.ex
defmodule Oauth2GoogleWeb.ErrorView do
  use Oauth2GoogleWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/oauth2Google_web/views/layout_view.ex
defmodule Oauth2GoogleWeb.LayoutView do
  use Oauth2GoogleWeb, :view
end

lib/oauth2Google_web/views/page_view.ex
defmodule Oauth2GoogleWeb.PageView do
  use Oauth2GoogleWeb, :view
end

lib/oauth2Google_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>OAuth2/Phoenix!</title>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <h1>Login Demo</h1>
      <%= if @current_user do %>
        <h2>Welcome, <%= @current_user.name %>!</h2>
        <img src="<%= @current_user.avatar %>" class="img-circle"/>
        <%= link "Logout", to: auth_path(@conn, :delete), method: :delete, class: "btn btn-danger" %>
      <% else %>
        <br>
        <br>

        <a class="btn btn-primary btn-lg" href="<%= auth_path @conn, :index, "google" %>">
          <i class="fa fa-google"></i>
          Sign in with Google
        </a>

        <a class="btn btn-primary btn-lg" href="<%= auth_path @conn, :index, "github" %>">
          <i class="fa fa-github"></i>
          Sign in with GitHub
        </a>

        <a class="btn btn-primary btn-lg" href="<%= auth_path @conn, :index, "facebook" %>">
          <i class="fa fa-facebook"></i>
          Sign in with Facebook
        </a>
      <% end %>
    </div>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script src="<%= static_path(@conn, "/js/app.js") %>"</script>
    <script>require("/web/static/app")</script>
  </body>
</html>

lib/oauth2Google_web/templates/layout/sign_in_sign_out.html.eex
<%= if @current_user do %>
  <h2>Welcome, <%= @current_user.name %>!</h2>
  <img src="<%= @current_user.avatar %>" class="img-circle"/>
  <%= link "Logout", to: auth_path(@conn, :delete, GitHub), method: :delete, class: "btn btn-danger" %>
<% else %>
  <br>
  <br>

  <a class="btn btn-primary btn-lg" href="<%= auth_path @conn, :index, "google" %>">
    <i class="fa fa-google"></i>
    Sign in with Google
  </a>

  <a class="btn btn-primary btn-lg" href="<%= auth_path @conn, :index, "github" %>">
    <i class="fa fa-github"></i>
    Sign in with GitHub
  </a>
<% end %>

lib/oauth2Google_web/templates/page/index.html.eex
<!-- web/templates/page/index.html.eex -->